title: Liwen Long's Homepage
page-top-title: LIwen Long
top-section-bg-text: Converging Technologies
home-subtitle: Liwen Long&ensp;|&ensp;龙俪闻
copyright-text: '&copy; Liwen Long 2024——2025. All Rights Reserved.'
